apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpinput2
  namespace: lcsystems
  labels:
    app: tcpinput2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpinput2
  template:
    metadata:
      name: tcpinput2
      namespace: lcsystems
      labels:
        app: tcpinput2
    spec:
      containers:
      - name: tcpinput2
        image: my2ndhead.com/k8s-skaffold/tcpinput2:7d2889d792a372c894a8cb00b21bbdd5250fa330885634ee86cd6ed9e0cdb36f
        ports:
          - name: tcpinput2
            containerPort: 12000
            hostPort: 12000
            nodePort: 12000
            protocol: TCP
      